pipeline {
    agent {
        node { label "maven" }
    }

    environment { QUAY = credentials('QUAY_USER') }

    stages {
        stage("Test") {
            steps {
                sh "./mvnw verify"
            }
        }

        stage("Build & Push Image") {
            steps {
                sh '''
                    ./mvnw quarkus:add-extension \
                    -Dextensions="container-image-jib"
                '''
                sh '''
                    ./mvnw package -DskipTests \
                    -Dquarkus.jib.base-jvm-image=quay.io/redhattraining/do400-java-alpine-openjdk11-jre:latest \
                    -Dquarkus.container-image.build=true \
                    -Dquarkus.container-image.registry=quay.io \
                    -Dquarkus.container-image.group=$QUAY_USR \
                    -Dquarkus.container-image.name=do400-home-automation-lab \
                    -Dquarkus.container-image.username=$QUAY_USR \
                    -Dquarkus.container-image.password="$QUAY_PSW" \
                    -Dquarkus.container-image.push=true
                '''
            }
        }

        stage('Deploy to TEST') {
            when { not { branch "main" } }

            steps {
                // Replace RHT_OCP4_DEV_USER with your lab user
                sh '''
                    oc rollout latest dc/home-automation \
                    -n RHT_OCP4_DEV_USER-home-automation-lab-test
                '''
            }
        }

        stage('Deploy to PROD') {
            when { branch "main" }

            steps {
                // Replace RHT_OCP4_DEV_USER with your lab user
                sh '''
                    oc rollout latest deploymentconfig/home-automation \
                    -n RHT_OCP4_DEV_USER-home-automation-lab-prod
                '''
            }
        }
    }
}
