apiVersion: v1
kind: Template
metadata:
  name: calculator-template
  annotations:
    description: "Quarkus Calculator"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: calculator
    spec:
      selector:
        matchLabels:
          app: calculator
      replicas: 1
      template:
        metadata:
          labels:
            app: calculator
        spec:
          containers:
            - name: calculator
              image: quay.io/${QUAY_USER_OR_GROUP}/${QUAY_REPOSITORY}:${APP_IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: calculator
      name: calculator
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: calculator
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: calculator
      labels:
        app: calculator
    spec:
      to:
        kind: Service
        name: calculator
      port:
        targetPort: 8080

parameters:
  - name: QUAY_USER_OR_GROUP
    description: "Quay User/Group"
    required: true
  - name: QUAY_REPOSITORY
    description: "Image repository"
    required: true
  - name: APP_IMAGE_TAG
    description: "Image Tag"
    required: false
    value: "latest"
