apiVersion: v1
kind: Template
metadata:
  name: shopping-cart-template
  annotations:
    description: "Shopping Cart Template"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: shopping-cart-v2
    spec:
      selector:
        matchLabels:
          app: shopping-cart-v2
      replicas: 1
      template:
        metadata:
          labels:
            app: shopping-cart-v2
        spec:
          containers:
            - name: shopping-cart-v2
              image: quay.io/${QUAY_USER_OR_GROUP}/do400-recover:${APP_IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: shopping-cart-v2
      name: shopping-cart-v2
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: shopping-cart-v2
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: shopping-cart-v2
      labels:
        app: shopping-cart-v2
    spec:
      to:
        kind: Service
        name: shopping-cart-v2
      port:
        targetPort: 8080

parameters:
  - name: QUAY_USER_OR_GROUP
    description: "Quay User/Group"
    required: true
  - name: APP_IMAGE_TAG
    description: "Image Tag"
    required: false
    value: "latest"
