apiVersion: v1
kind: Template
metadata:
  name: home-automation-template
  annotations:
    description: "Home Automation Application Template"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: home-automation
    spec:
      selector:
        matchLabels:
          app: home-automation
      replicas: 1
      template:
        metadata:
          labels:
            app: home-automation
        spec:
          containers:
            - name: home-automation
              image: quay.io/${QUAY_USER_OR_GROUP}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
      strategy:
        type: RollingUpdate
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: home-automation
      name: home-automation
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: home-automation
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: home-automation
      labels:
        app: home-automation
    spec:
      to:
        kind: Service
        name: home-automation
      port:
        targetPort: 8080

parameters:
  - name: QUAY_USER_OR_GROUP
    description: "Quay User/Group"
    required: true
  - name: APP_IMAGE_NAME
    description: "Image Name"
    required: false
    value: "home-automation"
  - name: APP_IMAGE_TAG
    description: "Image Tag"
    required: false
    value: "latest"
