pipeline {
  agent {
    label 'jenkins-agent-npm'
  }

  stages {
    stage ('NPM Install & Build') {
      steps {
        sh """
					cd exchange-cli
					npm install
          npm run build
				"""
      }
    }

    stage ('Functional Tests') {
      agent {
        label 'jenkins-agent-python'
      }
      steps {
        sh """
					pip install -r requirements.txt
					cd exchange-cli
          python -m pytest functional-test.py
        """
      }
    }
  }
}

