pipeline {
  agent {
    label 'jenkins-agent-npm'
  }

  stages {
    stage ('NPM Dependencies') {
      steps {
        sh """
					cd exchange-cli
					npm install
				"""
      }
    }

    stage ('Python Dependencies') {
      agent {
        label 'jenkins-agent-python'
      }
      steps {
        sh """
					cd exchange-cli
					pip install -r requirements.txt
        """
      }
    }

    stage ('Build') {
      steps {
        sh """
					cd exchange-cli
          npm run build
        """
      }
    }

    stage ('Functional Tests') {
      steps {
        sh """
					cd exchange-cli
          npm run test:functional
        """
      }
    }
  }
}

